Add font support
yamashi/CyberEngineTweaks pull request #407
Opened 2021-01-18 18:51 UTC by Rorschach1219

Configurable JSON file, supporting local font.  I tested Chinese, Japanese and Korean and worked well.

![汉字](https://user-images.githubusercontent.com/20067002/104952980-80108c00-5a00-11eb-8775-d42adf227bab.png)
![韩国](https://user-images.githubusercontent.com/20067002/104952997-8999f400-5a00-11eb-8e85-4788e7dcb998.png)
![日文](https://user-images.githubusercontent.com/20067002/104953007-8e5ea800-5a00-11eb-8029-c24534d5a18f.png)

2021-01-18 19:44 UTC, yamashi requested changes

2021-01-18 19:44 UTC, yamashi commented on src/console/Console.cpp
> -    ImGui::Begin("Cyber Engine Tweaks");
We are not going to add parenthesis for everything we add

2021-01-18 19:44 UTC, yamashi commented on src/d3d12/D3D12_Functions.cpp
> +                const ImWchar* glyph_ranges = io.Fonts->GetGlyphRangesDefault();
cpGlyphRanges

2021-01-18 19:44 UTC, yamashi commented on src/d3d12/D3D12_Functions.cpp
> +                if (font != NULL)
nullptr

2021-01-18 19:44 UTC, yamashi commented on src/d3d12/D3D12_Functions.cpp
> +                ImFont* font = io.Fonts->AddFontFromFileTTF(fontPath.string().c_str(), options.FontSize, NULL, glyph_ranges);
pFont, nullptr

2021-01-18 19:53 UTC, yamashi commented
It seems that FontSize relies on having a font specified, can't we make it so FontSize works even if we don't pass a FontPath?

2021-01-19 11:33 UTC, yamashi approved these changes

2021-01-19 11:34 UTC, merged

2021-01-19 11:36 UTC, yamashi commented
Thanks :)

2021-01-19 11:37 UTC, Rorschach1219 commented
The default font size is 13, which can be configured separately. can also set glyph ranges and font path at the same time
As shown below：
![2-13](https://user-images.githubusercontent.com/20067002/105029554-741edb80-5a8d-11eb-9149-81175f86e63b.png)
![2-18](https://user-images.githubusercontent.com/20067002/105029559-75500880-5a8d-11eb-8208-ff9812e5950a.png)