Add icon font support using FontAwesome4
yamashi/CyberEngineTweaks pull request #765
Opened 2022-12-01 04:47 UTC by Nats-ji

https://github.com/yamashi/CyberEngineTweaks/issues/755
```lua
ImGui.Text("icons: "..FA.ICON_MUSIC..FA.ICON_GLASS..FA.ICON_SEARCH..FA.ICON_QRCODE..FA.ICON_GITHUB..FA.ICON_FACEBOOK)
```
![image](https://user-images.githubusercontent.com/13299626/204967711-f0f42289-1517-4afa-a04d-77ab102c2a7c.png)

2022-12-01 09:44 UTC, WSSDude420 requested changes
Please, use latest version 6 if possible, and desktop version ideally instead of web one.

2022-12-01 09:44 UTC, WSSDude420 commented on src/scripting/Scripting.cpp
> +    luaVm.script("FA = require 'fontawesome/icons'", sol:: detail::default_chunk_name(), sol::load_mode::text);
I would probably name it IconGlyphs or something, is more expressive than FA

2022-12-01 09:47 UTC, WSSDude420 commented on scripts/fontawesome/icons.lua
> +    ICON_GLASS = '\u{f000}',
I dont know if you generated this somehow or where did you get this, but if you rename the enum like I wrote, remove the ICON_ prefix here please (so it doesnt look silly... IconGlyphs.ICON_GLASS is kinda weird)

2022-12-01 09:51 UTC, WSSDude420 commented on scripts/fontawesome/icons.lua
> +    ICON_GLASS = '\u{f000}',
Bonus points if you could make it like 

ICON_GLASS -> Glass
ICON_TH_LARGE -> ThLarge

so it fits more with a style of our other enums

2022-12-01 10:46 UTC, WSSDude420 commented
After looking around git a bit, couldn't we utilize this in some way?

https://github.com/juliettef/IconFontCppHeaders

This way, we could use it from C++ also (would like to make use of the icons in CET itself probably at some point)

2022-12-01 19:58 UTC, Nats-ji commented
> After looking around git a bit, couldn't we utilize this in some way?
> 
> https://github.com/juliettef/IconFontCppHeaders
> 
> This way, we could use it from C++ also (would like to make use of the icons in CET itself probably at some point)

not sure where to put it, so I just added it to the vendor folder.

> Please, use latest version 6 if possible

Let's just use version 4 since version 5/6 glyph range conflicts between light and solid. 😉

2022-12-02 10:36 UTC, WSSDude420 commented
Create new xmake package
https://github.com/xmake-io/xmake-repo

Vendor is very specific folder, would not add more stuff to it...

If you dont know how to do xmake package, can have a look later... Cant find time for CET in past few fays :(

2022-12-02 10:39 UTC, WSSDude420 commented
And in regards to FA6, would load the fonts from it in following order:
- brands
- regular
- solid

2022-12-02 10:44 UTC, WSSDude420 commented
In regards to FA6, would load in following order
- regular
- solid
- brands

maybe even skipped regular icons, looks like solid has them all (and they should look the best hopefully in current UI)

2022-12-04 15:56 UTC, Nats-ji commented
switched to font to https://materialdesignicons.com/

2022-12-04 16:36 UTC, WSSDude420 approved these changes

2022-12-04 16:41 UTC, merged